.circleci/config.yml
Makefile

Hello @nicks,
Please review the following commits I made in branch nicks/vet:
cdeba4b68467dd4628a84ac29ffb605628ec151e (2018-07-17 16:35:37 -0400)
ci: add go vet

ci: add go vet

---

internal/proc/proc.go
internal/proc/run.go
internal/proc/run_test.go

Please review the following commits I made in branch nicks/proc:
c2a720bc9201c16d1f82192771615f9632679093 (2018-07-17 18:20:49 -0400)
proc: add a simple run harness

proc: add a simple run harness

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/ci:
130a3f821e876c23f4279c8dd88a56af315a5d11 (2018-07-18 13:52:20 -0400)
readme: back to lowercase package names

readme: back to lowercase package names

---

cmd/pets/cmd.go
cmd/pets/dry-run.go
internal/mill/exec.go
internal/mill/exec_test.go

We are not sure if we have grievously broken anything

pets: WIP on dry-run

---

Gopkg.lock
internal/proc/proc.go
internal/proc/procfs.go
internal/proc/procfs_test.go
vendor/github.com/windmilleng/wmclient/LICENSE
vendor/github.com/windmilleng/wmclient/pkg/dirs/dirs.go

Please review the following commits I made in branch nicks/manager:
dd3650584ac9c3dd39d09de73cda49efe1140a9c (2018-07-19 17:04:41 -0400)
proc: write running procs to disk

proc: write running procs to disk

---

internal/proc/proc.go
internal/proc/procfs.go
internal/proc/procfs_test.go

Please review the following commits I made in branch nicks/alive:
0b38c4faadb22df16225c169809c4c57d47a7200 (2018-07-19 17:36:46 -0400)
proc: clean up processes that die in the background
dd3650584ac9c3dd39d09de73cda49efe1140a9c (2018-07-19 17:04:41 -0400)
proc: write running procs to disk

proc: clean up processes that die in the background

---

internal/proc/procfs_test.go
internal/proc/run.go
internal/proc/run_test.go

Please review the following commits I made in branch nicks/write:
08296a0402a2bd8d7d0d91244669d200674ca9cb (2018-07-24 10:35:29 -0400)
proc: when running a proc, write its state to disk
Code review reminders, by giving a LGTM you attest that:
* Commits are adequately tested
* Code is easy to understand and conforms to style guides
* Incomplete code is marked with TODOs
* Code is suitably instrumented with logging and metrics

proc: when running a proc, write its state to disk

---

cmd/pets/dry-run.go
internal/mill/exec.go
internal/mill/exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/merge:
da39783d8105531f318663b2402204e599929ea3 (2018-07-25 13:43:02 -0400)
mill: fix a merge conflict now that we use Runner

mill: fix a merge conflict now that we use Runner

---

internal/proc/proc.go
internal/proc/procfs.go
internal/proc/procfs_test.go

Please review the following commits I made in branch nicks/host:
8207137ac499c78c9c0b5442ef80951a66c49121 (2018-07-24 13:19:54 -0400)
proc: Add exposed host and port for making network connections

proc: Add exposed host and port for making network connections

---

internal/loader/go.go
internal/loader/go_test.go

Please review the following commits I made in branch nicks/loader:
5ae4ce107c319d8178a214a988dc44109a63a037 (2018-07-24 15:09:12 -0400)
loader: Add a loader for Go repos

loader: Add a loader for Go repos

---

internal/mill/exec.go
internal/mill/exec_test.go
internal/proc/run.go
internal/proc/run_test.go

Hi, this is the early work for the pets start function. I find myself getting a little confused on functionality because I'm not sure if I'm running these correctly. Also, there's no test yet. But it exists!

Early start function works (?)

---

internal/mill/exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/testing:
9ac1d0310c3ef17698ed6c9f2fb9fc156df31729 (2018-07-26 19:51:04 -0400)
testing: some minor test cleanup

testing: some minor test cleanup

---

internal/mill/exec.go
internal/mill/exec_test.go

Please review the following commits I made in branch nicks/recurse:
3b0139ff12bf8b74f99a03e7a40d44b027bd1245 (2018-07-25 17:09:48 -0400)
mill: recursive execution of loaded Petsfiles

mill: recursive execution of loaded Petsfiles

---

internal/school/school.go
internal/school/school_test.go
internal/service/service.go

Please review the following commits I made in branch nicks/registry:
388e2404216b427cc2ff96fbbf20a38e2c27e1b0 (2018-07-26 16:19:59 -0400)
school: add a PetSchool, the place to raise new pets

school: add a PetSchool, the place to raise new pets

---

internal/mill/exec.go

Hello @nicks,
Please review the following commits I made in branch nicks/file:
8951b833fea99074225ea7a7c6c8b54bed1e2f0a (2018-07-27 18:05:31 -0400)
mill: even more simplification of threads!

mill: even more simplification of threads!

---

internal/proc/procfs.go
internal/proc/procfs_test.go
internal/school/school.go
internal/school/school_test.go

Hello @pmt,
Please review the following commits I made in branch nicks/key:
2ae1dc0fdd9cea860dc16d79042732a61182110f (2018-07-30 19:00:37 -0400)
school: write the name of the service to the procfs database

school: write the name of the service to the procfs database

---

internal/mill/exec.go
internal/mill/exec_test.go

Hello @pmt,
Please review the following commits I made in branch nicks/registry2:
e483871acdf62c2669eec5d36a7a2e9b4eaacfdb (2018-07-31 15:29:14 -0400)
mill: add a register() function

mill: add a register() function

---

cmd/pets/cmd.go
cmd/pets/down.go

pets: pets down command

---

Makefile
cmd/pets/cmd.go
cmd/pets/up.go

Hello @pmt,
Please review the following commits I made in branch nicks/up:
4a8d8537f0e19b52b61b5a9ade8a223623da8412 (2018-07-31 16:12:28 -0400)
pets: add 'pets up'

pets: add 'pets up'

---

internal/mill/exec.go
internal/mill/exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/addr:
0ce5b279826616945642f4a4216654e8c4c6257f (2018-07-31 19:08:31 -0400)
pets: add a 'host' for convenience to the process

pets: add a 'host' for convenience to the process

---

internal/mill/exec.go
internal/mill/exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/cwd:
66c78f3a0644690d1185e32f1c9a8a1e72687ca8 (2018-07-31 19:26:10 -0400)
pets: run/start should execute things relative to the current petsfile

pets: run/start should execute things relative to the current petsfile

---

internal/mill/exec.go
internal/mill/exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/dupe:
42a11e28d7341f60101006caddd64d7aeebf4feb (2018-08-01 11:35:23 -0400)
mill: fix up the error message for duplicate services

mill: fix up the error message for duplicate services

---

cmd/pets/cmd.go
cmd/pets/down.go
cmd/pets/list.go
cmd/pets/up.go
internal/mill/exec.go
internal/mill/exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/diamond:
f8d9516298df607194d9058b8eb156d97b204228 (2018-08-01 12:22:21 -0400)
mill: handle load cycles and duplicate loads

mill: handle load cycles and duplicate loads

---

Gopkg.lock
vendor/github.com/windmilleng/wmclient/pkg/dirs/dirs.go

Hello @nicks,
Please review the following commits I made in branch nicks/update:
24850616392e75e4aab8eab7971b02aa61c3f318 (2018-08-01 17:46:32 -0400)
vendor: update wmclient dep

vendor: update wmclient dep

---

cmd/pets/list.go
internal/proc/proc.go
internal/proc/procfs_test.go

pets: show time and not PID on list

---

internal/mill/exec.go
internal/mill/exec_test.go
internal/proc/procfs.go
internal/proc/run.go
internal/service/service.go

Hello @pmt,
Please review the following commits I made in branch nicks/io:
2a48452d005f7ff6f6833cf4cac10c217ac56e01 (2018-08-01 17:53:29 -0400)
mill: 'start()' should write to a log file

mill: 'start()' should write to a log file

---

cmd/pets/cmd.go
cmd/pets/logs.go
internal/mill/exec_test.go
internal/proc/proc.go
internal/school/school.go

Hello @pmt,
Please review the following commits I made in branch nicks/logs:
1d482bc3156affb6c0da282c1afdba81671813b2 (2018-08-02 11:44:15 -0400)
pets: add a 'logs' command

pets: add a 'logs' command

---

Makefile
internal/mill/exec.go
internal/mill/exec_test.go
internal/proc/procfs.go
internal/proc/procfs_test.go
internal/proc/run_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/health3:
40e74616c273dfcfc06093513d66d860d1dcd17a (2018-08-02 16:26:37 -0400)
procfs: clean up process management a bit to get rid of zombies

procfs: clean up process management a bit to get rid of zombies

---

Makefile
internal/health/health.go
internal/mill/exec.go
internal/mill/exec_test.go
internal/proc/proc.go

Hello @pmt,
Please review the following commits I made in branch nicks/health:
0b06db0135bd6a74e47b014d23b7d6e5f01f8652 (2018-08-02 17:18:36 -0400)
health: Add health checks to pets

health: Add health checks to pets

---

README.md

Hello @nicks,
Please review the following commits I made in branch nicks/readme:
ff4d200a2826fc902b44daaf5725d800f1615455 (2018-08-03 14:16:26 -0400)
initial readme skeleton

initial readme skeleton

---

internal/school/school.go
internal/school/school_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/with:
3a51a7cb45f2ddd5e23c5aefdfd446802578009c (2018-08-03 15:14:55 -0400)
school: add an api for overrides

school: add an api for overrides

---

cmd/pets/list.go
cmd/pets/provider.go
cmd/pets/up.go
internal/mill/exec.go
internal/mill/exec_test.go
internal/proc/run.go

Finally after many years, dry-run works!?

Pets: dry run

---

Gopkg.lock
cmd/pets/cmd.go
cmd/pets/down.go
cmd/pets/up.go
main.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/analytics.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/cli.go
vendor/github.com/windmilleng/wmclient/pkg/analytics/opt.go

Hello @maiamcc, @pmt,
Please review the following commits I made in branch nicks/analytics:
093601507024880bb0e65de73e82d9be9db12a60 (2018-08-03 14:42:10 -0400)
pets: add analytics

pets: add analytics

---

cmd/pets/down.go
internal/proc/procfs.go
internal/service/service.go

Hello @pmt, @yuindustries,
Please review the following commits I made in branch nicks/down:
48aacd1bdb205b2c169570adfc111e12ebc023f8 (2018-08-06 13:39:11 -0400)
pets: make pets down more error-resistant

pets: make pets down more error-resistant

---

docs/config.md

Hello @pmt, @yuindustries,
Please review the following commits I made in branch nicks/docs:
c5a339953c968bf1d057b506e1801536a933f759 (2018-08-06 10:55:24 -0400)
docs: write configuration docs

docs: write configuration docs

---

.circleci/config.yml
internal/mill/exec_test.go

Hello @nicks,
Please review the following commits I made in branch nicks/macos:
f1ea8d54ed339f71c4702e051619814e5574b94a (2018-08-07 11:19:44 -0400)
circleci: build macos

circleci: build macos

---

.circleci/config.yml

Hello @nicks,
Please review the following commits I made in branch nicks/get:
086b496f14dac709f89f261649bbde5306e79a6c (2018-08-07 13:51:17 -0400)
pre-fetch blorg frontend to help with test flakiness

pre-fetch blorg frontend to help with test flakiness
